services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.grpc
    ports:
      - "50051:50051"
    environment:
      - CONFIG_FILE=/root/config/config.yaml
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    volumes:
      - ./api/config:/root/config
    depends_on:
      - db
  gateway:
    build:
      context: ./api
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    depends_on:
      - api
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    volumes:
      - ./worker/.env:/app/.env
    depends_on:
      - db
  db:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  default:
    name: text2manim-network