// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Generation is the predicate function for generation builders.
type Generation func(*sql.Selector)
