name: Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  golangci:
    name: lint-golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: latest
          working-directory: ./api

  ruff:
    name: lint-ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sksat/setup-rye@v0.29.0
      # ruffのセットアップ
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
          src: './api'
      - name: Sync Rye
        run: rye sync

  buf-lint:
    name: lint-protobuf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.35.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1.1.1

  editorconfig-checker:
    name: lint-editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2

  markdown-lint:
    name: lint-markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yml
